on:
  push:
    branches:
      - integ-tests

name: Integration Test

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Express Service
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsdeplo-cgLSI6gSDu11:381467b8-9ee5-433e-a264-4e289362cc5d

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsDeployExpressIntegrationTests
        role-session-name: deploy_express_integration_tests
        aws-region: us-west-2

    - name: Deploy Amazon ECS Express Service
      uses: aws-actions/amazon-ecs-deploy-express-service@1cd950681bc125e2c0d50696c5d53fc2c0bacfd4
      with:
        service-name: github-actions-deploy-express-integ-test
        image: public.ecr.aws/nginx/nginx:latest
        execution-role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole
        infrastructure-role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsInfrastructureRole
        cluster: github-actions-deploy-express-integ-test
